using System.Collections.Generic;
using LedCSharp;

namespace CodeChicken.RGBKeyboard
{
	public static class KeyCodeMap
	{
		public static Dictionary<VK, keyboardNames> map = new Dictionary<VK, keyboardNames> {
			//{ VK.VOLUME_MUTE, keyboardNames. }
			{VK.ESCAPE, keyboardNames.ESC},
			{VK.F1, keyboardNames.F1},
			{VK.F2, keyboardNames.F2},
			{VK.F3, keyboardNames.F3},
			{VK.F4, keyboardNames.F4},
			{VK.F5, keyboardNames.F5},
			{VK.F6, keyboardNames.F6},
			{VK.F7, keyboardNames.F7},
			{VK.F8, keyboardNames.F8},
			{VK.F9, keyboardNames.F9},
			{VK.F10, keyboardNames.F10},
			{VK.F11, keyboardNames.F11},
			{VK.F12, keyboardNames.F12},
			{VK.SNAPSHOT, keyboardNames.PRINT_SCREEN},
			{VK.SCROLL, keyboardNames.SCROLL_LOCK},
			{VK.PAUSE, keyboardNames.PAUSE_BREAK},
			//{ VK.MEDIA_PLAY_PAUSE, keyboardNames. },
			//{ VK.MEDIA_STOP, keyboardNames. },
			//{ VK.MEDIA_PREV_TRACK, keyboardNames. },
			//{ VK.MEDIA_NEXT_TRACK, keyboardNames. },
			{VK.OEM_3, keyboardNames.TILDE},
			{VK.KEY_1, keyboardNames.ONE},
			{VK.KEY_2, keyboardNames.TWO},
			{VK.KEY_3, keyboardNames.THREE},
			{VK.KEY_4, keyboardNames.FOUR},
			{VK.KEY_5, keyboardNames.FIVE},
			{VK.KEY_6, keyboardNames.SIX},
			{VK.KEY_7, keyboardNames.SEVEN},
			{VK.KEY_8, keyboardNames.EIGHT},
			{VK.KEY_9, keyboardNames.NINE},
			{VK.KEY_0, keyboardNames.ZERO},
			{VK.OEM_MINUS, keyboardNames.MINUS},
			{VK.OEM_PLUS, keyboardNames.EQUALS},
			{VK.BACK, keyboardNames.BACKSPACE},
			{VK.INSERT, keyboardNames.INSERT},
			{VK.HOME, keyboardNames.HOME},
			{VK.PRIOR, keyboardNames.PAGE_UP},
			{VK.NUMLOCK, keyboardNames.NUM_LOCK},
			{VK.DIVIDE, keyboardNames.NUM_SLASH},
			{VK.MULTIPLY, keyboardNames.NUM_ASTERISK},
			{VK.SUBTRACT, keyboardNames.NUM_MINUS},
			{VK.TAB, keyboardNames.TAB},
			{VK.KEY_Q, keyboardNames.Q},
			{VK.KEY_W, keyboardNames.W},
			{VK.KEY_E, keyboardNames.E},
			{VK.KEY_R, keyboardNames.R},
			{VK.KEY_T, keyboardNames.T},
			{VK.KEY_Y, keyboardNames.Y},
			{VK.KEY_U, keyboardNames.U},
			{VK.KEY_I, keyboardNames.I},
			{VK.KEY_O, keyboardNames.O},
			{VK.KEY_P, keyboardNames.P},
			{VK.OEM_4, keyboardNames.OPEN_BRACKET},
			{VK.OEM_6, keyboardNames.CLOSE_BRACKET},
			{VK.OEM_5, keyboardNames.BACKSLASH},
			{VK.DELETE, keyboardNames.KEYBOARD_DELETE},
			{VK.END, keyboardNames.END},
			{VK.NEXT, keyboardNames.PAGE_DOWN},
			{VK.NUMPAD7, keyboardNames.NUM_SEVEN},
			{VK.NUMPAD8, keyboardNames.NUM_EIGHT},
			{VK.NUMPAD9, keyboardNames.NUM_NINE},
			{VK.ADD, keyboardNames.NUM_PLUS},
			{VK.CAPITAL, keyboardNames.CAPS_LOCK},
			{VK.KEY_A, keyboardNames.A},
			{VK.KEY_S, keyboardNames.S},
			{VK.KEY_D, keyboardNames.D},
			{VK.KEY_F, keyboardNames.F},
			{VK.KEY_G, keyboardNames.G},
			{VK.KEY_H, keyboardNames.H},
			{VK.KEY_J, keyboardNames.J},
			{VK.KEY_K, keyboardNames.K},
			{VK.KEY_L, keyboardNames.L},
			{VK.OEM_1, keyboardNames.SEMICOLON},
			{VK.OEM_7, keyboardNames.APOSTROPHE},
			{VK.RETURN, keyboardNames.ENTER},
			{VK.NUMPAD4, keyboardNames.NUM_FOUR},
			{VK.NUMPAD5, keyboardNames.NUM_FIVE},
			{VK.NUMPAD6, keyboardNames.NUM_SIX},
			{VK.LSHIFT, keyboardNames.LEFT_SHIFT},
			{VK.KEY_Z, keyboardNames.Z},
			{VK.KEY_X, keyboardNames.X},
			{VK.KEY_C, keyboardNames.C},
			{VK.KEY_V, keyboardNames.V},
			{VK.KEY_B, keyboardNames.B},
			{VK.KEY_N, keyboardNames.N},
			{VK.KEY_M, keyboardNames.M},
			{VK.OEM_COMMA, keyboardNames.COMMA},
			{VK.OEM_PERIOD, keyboardNames.PERIOD},
			{VK.OEM_2, keyboardNames.FORWARD_SLASH},
			{VK.RSHIFT, keyboardNames.RIGHT_SHIFT},
			{VK.UP, keyboardNames.ARROW_UP},
			{VK.NUMPAD1, keyboardNames.NUM_ONE},
			{VK.NUMPAD2, keyboardNames.NUM_TWO},
			{VK.NUMPAD3, keyboardNames.NUM_THREE},
			{LLKeyboardHook.NUMPAD_RETURN, keyboardNames.NUM_ENTER},
			{VK.LCONTROL, keyboardNames.LEFT_CONTROL},
			{VK.LWIN, keyboardNames.LEFT_WINDOWS},
			{VK.LMENU, keyboardNames.LEFT_ALT},
			{VK.SPACE, keyboardNames.SPACE},
			{VK.RMENU, keyboardNames.RIGHT_ALT},
			{VK.RWIN, keyboardNames.RIGHT_WINDOWS},
			{VK.APPS, keyboardNames.APPLICATION_SELECT},
			{VK.RCONTROL, keyboardNames.RIGHT_CONTROL},
			{VK.LEFT, keyboardNames.ARROW_LEFT},
			{VK.DOWN, keyboardNames.ARROW_DOWN},
			{VK.RIGHT, keyboardNames.ARROW_RIGHT},
			{VK.NUMPAD0, keyboardNames.NUM_ZERO},
			{VK.DECIMAL, keyboardNames.NUM_PERIOD},
		};
	}
}
